### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ThunderBeast30** [booksaw/BetterTeams#289] opened 2021-12-08 16:07 UTC
**Describe the bug**
hey i have added better teams but when i try to do team kick or team ban or team color something like its comes an internal error occured while using this command and i really need to kick one person from my team and its only happening to my team not anyone else team idk how to fix it pls help me
**To Reproduce**
Steps to reproduce the behaviour:
1. Run command...
2. 

**Expected behaviour**
i want it to work like when i do /team color gold i want it to update in tab 

**Screenshots**

**Details**
Please provide the following details about your server set-up:
- Spigot version (found by BetterTeams /version):
- BetterTeams version (found by running /version BetterTeams latest one 
): 

**Additional context**
Add any other context about the problem here
```.
net.skinsrestorer.shared.exception.UpdateException: Download returned status #302
356 at net.skinsrestorer.bukkit.utils.UpdateDownloaderGithub.download(UpdateDownloaderGithub.java:62) ~[?:?]
357 at net.skinsrestorer.bukkit.utils.UpdateDownloaderGithub.lambda$downloadAsync$0(UpdateDownloaderGithub.java:47) ~[?:?]
358 at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:82) [minecraft_server.jar:3284-Spigot-3892929-0ebef35]
359 at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [minecraft_server.jar:3284-Spigot-3892929-0ebef35]
360 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
361 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
362 at java.lang.Thread.run(Thread.java:831) [?:?]
363 [01:17:39] [Server thread/WARN]: An avaliable team cannot be found, be prepared for a lot of errors. (this should never happen, and should always be reported to booksaw)
364 [01:17:39] [Server thread/WARN]: This catch is merely here to stop the server crashing
365 [01:17:39] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to BetterTeams v4.2.1
366 org.bukkit.event.EventException: null
367 at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[minecraft_server.jar:3284-Spigot-3892929-0ebef35]
368 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[minecraft_server.jar:3284-Spigot-3892929-0ebef35]
369 at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[minecraft_server.jar:3284-Spigot-3892929-0ebef35]
370 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[minecraft_server.jar:3284-Spigot-3892929-0ebef35]
371 at net.minecraft.server.players.PlayerList.a(PlayerList.java:276) ~[minecraft_server.jar:3284-Spigot-3892929-0ebef35]
372 at net.minecraft.server.network.LoginListener.a(LoginListener.java:192) ~[minecraft_server.jar:3284-Spigot-3892929-0ebef35]
373 at net.minecraft.server.network.LoginListener.c(LoginListener.java:179) ~[minecraft_server.jar:3284-Spigot-3892929-0ebef35]
374 at net.minecraft.server.network.LoginListener.tick(LoginListener.java:74) ~[minecraft_server.jar:3284-Spigot-3892929-0ebef35]
375 at net.minecraft.network.NetworkManager.a(NetworkManager.java:246) ~[minecraft_server.jar:3284-Spigot-3892929-0ebef35]
376 at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:172) ~[minecraft_server.jar:3284-Spigot-3892929-0ebef35]
377 at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1336) ~[minecraft_server.jar:3284-Spigot-3892929-0ebef35]
378 at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:438) ~[minecraft_server.jar:3284-Spigot-3892929-0ebef35]
379 at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1217) ~[minecraft_server.jar:3284-Spigot-3892929-0ebef35]
380 at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1050) ~[minecraft_server.jar:3284-Spigot-3892929-0ebef35]
381 at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305) ~[minecraft_server.jar:3284-Spigot-3892929-0ebef35]
382 at java.lang.Thread.run(Thread.java:831) [?:?]
383 Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.scoreboard.Team.addEntry(String)" because the return value of "com.booksaw.betterTeams.Team.getScoreboardTeam(org.bukkit.scoreboard.Scoreboard)" is null
384 at com.booksaw.betterTeams.events.MCTeamManagement.displayBelowName(MCTeamManagement.java:62) ~[?:?]
385 at com.booksaw.betterTeams.events.MCTeamManagement.playerJoinEvent(MCTeamManagement.java:109) ~[?:?]
386 at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
387 at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
388 at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
389 at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
390 at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[minecraft_server.jar:3284-Spigot-3892929-0ebef35]
```

**Comment by Dzyk0s** [comment] 2021-12-20 17:08
Hola, mi nombre es [wWw] Javier Camus, Ceo de mc.Anarkhium.cl
vengo por un Problema de Prefix,
yo hace 1 hora Jugaba Minecraft con la versión de Servidor 1.18 junto a la versión de BetterTeams 4.2.1, y el plugin iba correcto...
En el Chat a un Jugador al escribir se le proponía este Sistema de Prefix's; "[Equipo] [Rango en Servidor] [Nombre del Jugador] : [Mensaje]" el descriptivo "[Equipo]" es el Prefix de BetterTeams, el cual en la Versión de Servidor 1.18 Sí se veía el "[Nombre de Equipo]", en mi caso "[Staff]" en el siguiente orden "[Staff] [Dueño] wWw: hola]",
pero al momento de Actualizar el Servidor a 1.18.1; el Prefix de BetterTeams desapareció y ahora solo aparece este Sistema de Prefix "[Dueño] wWw: hola" sin aparecer el Prefix de "[Nombre de Equipo]".

Se me plantea este error en la consola cuando ejecuto ciertos Comandos del Plugin:

[13:54:10] [Async Chat Thread - #0/ERROR]: Could not pass event AsyncPlayerChatEvent to BetterTeams v4.2.1
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) [spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) [spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.PlayerConnection.chat(PlayerConnection.java:1860) [spigot-1.18.1-R0.1-SNAPSHOT.jar:3368-Spigot-8965a50-2a2caa7]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1794) [spigot-1.18.1-R0.1-SNAPSHOT.jar:3368-Spigot-8965a50-2a2caa7]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1760) [spigot-1.18.1-R0.1-SNAPSHOT.jar:3368-Spigot-8965a50-2a2caa7]
        at net.minecraft.network.protocol.game.PacketPlayInChat$1.run(PacketPlayInChat.java:40) [spigot-1.18.1-R0.1-SNAPSHOT.jar:3368-Spigot-8965a50-2a2caa7]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.util.UnknownFormatConversionException: Conversion = ' '
        at java.util.Formatter.parse(Formatter.java:2750) ~[?:?]
        at java.util.Formatter.format(Formatter.java:2671) ~[?:?]
        at java.util.Formatter.format(Formatter.java:2625) ~[?:?]
        at java.lang.String.format(String.java:4140) ~[?:?]
        at com.booksaw.betterTeams.events.ChatManagement$PrefixType.getUpdatedFormat(ChatManagement.java:105) ~[?:?]
        at com.booksaw.betterTeams.events.ChatManagement.onChat(ChatManagement.java:74) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        ... 12 more
        
        
        
        Eliminé "messages.yml y es_mx", Configuré el Prefix de "config.yml" a "false" y a "true" y aún así no aparece nada... en esa sección por "default" estaba con el nombre de "name" desde un comienzo.
        
        "&7[%s&7] &r%s"
        
        Este es el "PrefixSyntax" que poseo...
        
        Muchas Gracias por la atención, para mi es un problema importante ya que estoy a "Días" de Abrir mi Servidor al Público.
        Discord: wWw#4189

**Comment by booksaw** [comment] 2021-12-29 10:05
This bug has been fixed and the patch will be included in the next update. Thank you for reporting.

**Closed by booksaw** 2021-12-29 10:05 UTC
Labels: bug
