### ISSUE TITLE
[FEATURE] Command Permissions

### ISSUE THREAD

**Issue by Gorbuxxx** [booksaw/BetterTeams#92] opened 2021-03-30 22:40 UTC
PLEASE add a way for normal team members to use the create and remove chest command but still have it so only owners can use the remove all chests command.
Also when you create another alias for the command text ( like /t for example) it only lets op's use it. Members still have to use /team

Other than that the plugin is perfect. Thank You!

**Comment by booksaw** [comment] 2021-03-31 09:01
"Also when you create another alias for the command text ( like /t for example) it only lets op's use it. Members still have to use /team" 
This is not a bug and I have replied to you about it on the discord. 

"PLEASE add a way for normal team members to use the create and remove chest command but still have it so only owners can use the remove all chests command." 
I am going to reskin this issue as requesting a method to change which ranks in a team have permissions to do what in general instead of specifically for chest claiming. 
The intention is to make another yaml called permissions.yml which stores the commands only owners / admins / standard users can do.

**Comment by booksaw** [comment] 2021-04-16 13:04
This feature has been implemented and will be included in the next update.

**Closed by booksaw** 2021-04-16 13:04 UTC
Labels: enhancement
