### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by giantfurkii** [booksaw/BetterTeams#191] opened 2021-07-17 07:10 UTC
![image](https://user-images.githubusercontent.com/78488589/126029189-cfb6b5a8-b1ce-4130-b5f4-f633f2aec723.png)
I get this error even though I created the folder from scratch.

**Comment by booksaw** [comment] 2021-07-17 08:21
this is a duplicate of #189

**Closed by booksaw** 2021-07-17 08:21 UTC
Labels: bug
