### ISSUE TITLE
[BUG] /teama reload

### ISSUE THREAD

**Issue by dogi-dogi** [booksaw/BetterTeams#212] opened 2021-08-02 13:45 UTC
v 1.12.2 paper spigot 
teamplugin v 4.0.4

just use /teama reload

[23:44:05 INFO]: [BetterTeams] Checking if the file config.yml is up to date
[23:44:05 INFO]: [BetterTeams] File is up to date
[23:44:05 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'teama reload' in com.booksaw.betterTeams.BooksawCommand(teamadmin)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:162) ~[Paper.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685) ~[Paper.jar:git-Paper-1618]        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1492) ~[Paper.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1297) ~[Paper.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[Paper.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[Paper.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[Paper.jar:git-Paper-1618]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_301]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_301]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[Paper.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[Paper.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[Paper.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[Paper.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[Paper.jar:git-Paper-1618]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_301]
Caused by: java.lang.NoClassDefFoundError: com/sk89q/worldguard/WorldGuard
        at com.booksaw.betterTeams.integrations.WorldGaurdManager.<init>(WorldGaurdManager.java:26) ~[?:?]
        at com.booksaw.betterTeams.Main.onLoad(Main.java:151) ~[?:?]
        at com.booksaw.betterTeams.Main.reload(Main.java:287) ~[?:?]
        at com.booksaw.betterTeams.commands.teama.ReloadTeama.onCommand(ReloadTeama.java:17) ~[?:?]
        at com.booksaw.betterTeams.commands.ParentCommand.onCommand(ParentCommand.java:135) ~[?:?]
        at com.booksaw.betterTeams.BooksawCommand.execute(BooksawCommand.java:56) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152) ~[Paper.jar:git-Paper-1618]
        ... 14 more

**Comment by booksaw** [comment] 2021-08-02 14:34
What version of worldgaurd are you using?

**Comment by dogi-dogi** [comment] 2021-08-03 14:08
> 어떤 버전의 worldgaurd를 사용하고 있습니까?

worldguard-bukkit-6.2.2

1.12.2 The version's maximum supported plugin.

**Comment by booksaw** [comment] 2021-08-04 12:39
Alright, this is a known issue, please see the linked issue for more details.
#173

**Comment by booksaw** [comment] 2021-08-04 12:39
duplicate of #173

**Closed by booksaw** 2021-08-04 12:39 UTC
Labels: bug

**Comment by booksaw** [comment] 2021-08-04 12:40
Duplicate of #173
