### ISSUE TITLE
[FEATURE] WARS

### ISSUE THREAD

**Issue by TrookiGaming** [booksaw/BetterTeams#520] opened 2023-11-12 12:49 UTC
### What is the feature request for?

It would be great if there was /team war to declare war on a specific team
And for example, the one who obtains the most kills from the other team in a certain time wins.

To do this, some ideas that come to mind
- Know the coordinates of the enemy /team home (necessary requirement to declare a war, have the /team home, you could still disable it in the config)
- Make both teams have an aura throughout the war and only the enemy team can see them (disable or not in the config)
- That both teams can bet an amount of money and whoever wins the war takes it all

I hope you consider it, it would be incredible

### Feature requests are not going to be implemented by booksaw, instead you will have to find another developer to make a pull request to implement the feature.

- [X] I understand

**Comment by TurgutHarunArslan** [comment] 2023-12-15 12:39
You can check my plugin its kinda similiar to what you want
https://www.spigotmc.org/resources/team-wars.113973/

**Comment by booksaw** [comment] 2024-02-24 13:26
Marking as a duplicate of #526 as though it is more recent, it has more discussion

**Closed by booksaw** 2024-02-24 13:26 UTC
Labels: enhancement (uncategorised)
