### ISSUE TITLE
[BUG] Team Name can be stored as null

### ISSUE THREAD

**Issue by Angalets** [booksaw/BetterTeams#178] opened 2021-07-06 17:12 UTC
**Describe the bug**
The plugin works well, but not for all players, a user will try to join a team but does not allow her, when they invite her she does not let her in, when she tries to make a team she tells her that she must first leave the one she has, but she is not in No team, when I try to put the administrator commands like / teama leave or / teama join, I get an error in the chat for each letter I write that says `` An internal error occurred while attemping to tab-complete this command ''

**To Reproduce**
Steps to reproduce the behaviour:
1. Run command /teama join or /teama leave
2. This happens for a player named ''marnunu'', or when I try to put the commands of /teama,
![error](https://user-images.githubusercontent.com/81670934/124640594-78c02c00-de42-11eb-9975-f382f800705e.PNG)
![version](https://user-images.githubusercontent.com/81670934/124640645-8f668300-de42-11eb-8c4e-577ce42464d4.PNG)
 It hasn't happened to me with other players yet I think

**Expected behaviour**
I want to make it leave the team that says it is, or I want to put it in a team, but the plugin does not let me

**Screenshots**

**Details**
Please provide the following details about your server set-up:
- Spigot version (found by running /version):
- BetterTeams version (found by running /version BetterTeams): 
- In the screenshots

**Additional context**
https://pastebin.com/Jm6ncPJd

**Comment by booksaw** [comment] 2021-07-06 19:45
Hi to help with debugging the error could you look into the problem a little more please. 
The UUID of marnnu is found here: https://mcuuid.net/?q=marnunu but the player you are referencing in the screenshotted command has a slightly different name, so im not sure which is accurate. 

in the teams.yml file, search for their uuid (including dashs) this can be done by using ctrl + f
on the same line that their uuid appears there will be a second uuid, copy that uuid and search the betterteams folder for a file called that uuid.
There should be a yml file that uuid. please could you send a screenshot of that file.

**Comment by JakeHasSkill** [comment] 2021-07-13 22:40
I think I have the same problem. Someone on my server isn't able to leave his team, but he doesn't appear on the team using /team info. He can't join another team because it says he needs to leave his current team first. When he tries to leave (in any way, including /team leave, /team kick, /teamadmin leave) it gives this error:

[16:28:06] [Server thread/INFO]: Brite__ issued server command: /team leave
[16:28:06] [Server thread/WARN]: An avaliable team cannot be found, be prepared for a lot of errors. (this should never happen, and should always be reported to booksaw)
[16:28:06] [Server thread/WARN]: This catch is merely here to stop the server crashing
[16:28:06] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'team leave' in com.booksaw.betterTeams.BooksawCommand(team)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:156) ~[spigot.jar:3170-Spigot-a483d2c-ec116f6]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:760) ~[spigot.jar:3170-Spigot-a483d2c-ec116f6]
	at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:1944) ~[spigot.jar:3170-Spigot-a483d2c-ec116f6]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1783) ~[spigot.jar:3170-Spigot-a483d2c-ec116f6]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1764) ~[spigot.jar:3170-Spigot-a483d2c-ec116f6]
	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46) ~[spigot.jar:3170-Spigot-a483d2c-ec116f6]
	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot.jar:3170-Spigot-a483d2c-ec116f6]
	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30) ~[spigot.jar:3170-Spigot-a483d2c-ec116f6]
	at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot.jar:3170-Spigot-a483d2c-ec116f6]
	at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151) ~[spigot.jar:3170-Spigot-a483d2c-ec116f6]
	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot.jar:3170-Spigot-a483d2c-ec116f6]
	at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(SourceFile:125) ~[spigot.jar:3170-Spigot-a483d2c-ec116f6]
	at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1125) ~[spigot.jar:3170-Spigot-a483d2c-ec116f6]
	at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1118) ~[spigot.jar:3170-Spigot-a483d2c-ec116f6]
	at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(SourceFile:134) ~[spigot.jar:3170-Spigot-a483d2c-ec116f6]
	at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1102) ~[spigot.jar:3170-Spigot-a483d2c-ec116f6]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1031) ~[spigot.jar:3170-Spigot-a483d2c-ec116f6]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[spigot.jar:3170-Spigot-a483d2c-ec116f6]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.scoreboard.Team.removeEntry(String)" because the return value of "com.booksaw.betterTeams.Team.getScoreboardTeam(org.bukkit.scoreboard.Scoreboard)" is null
	at com.booksaw.betterTeams.events.MCTeamManagement.remove(MCTeamManagement.java:100) ~[?:?]
	at com.booksaw.betterTeams.team.MemberListComponent.remove(MemberListComponent.java:63) ~[?:?]
	at com.booksaw.betterTeams.Team.removePlayer(Team.java:611) ~[?:?]
	at com.booksaw.betterTeams.Team.removePlayer(Team.java:599) ~[?:?]
	at com.booksaw.betterTeams.commands.team.LeaveCommand.onCommand(LeaveCommand.java:26) ~[?:?]
	at com.booksaw.betterTeams.commands.presets.TeamSubCommand.onCommand(TeamSubCommand.java:39) ~[?:?]
	at com.booksaw.betterTeams.commands.ParentCommand.onCommand(ParentCommand.java:135) ~[?:?]
	at com.booksaw.betterTeams.BooksawCommand.execute(BooksawCommand.java:56) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot.jar:3170-Spigot-a483d2c-ec116f6]
	... 18 more

**Comment by booksaw** [comment] 2021-07-17 09:01
This bug has been fixed and the patch will be included in the next update. Thank you for reporting.

**Closed by booksaw** 2021-07-17 09:01 UTC
Labels: In Next Update, bug
