### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by DarknightHD** [booksaw/BetterTeams#185] opened 2021-07-13 16:33 UTC
When I tried to update my Better Teams plugin to the latest one from version 3.1.26 to the latest one,
the plugin stops working. here's the screenshot of the error.

![image](https://user-images.githubusercontent.com/67949991/125490717-b043a0a3-b9aa-43a9-bd50-9eada8b02f3a.png)

**Comment by booksaw** [comment] 2021-07-17 09:13
This bug has been fixed for the next update.

This will have been caused by a player having `:` in their name, if you restart the conversion to the new storage method while using version 4.0.3 this will be fixed automatically. 

You will have to restore the old team first details on how to do this attached below: 
How do I restore the backed up betterTeams file from before update 4.0.0?
1. Stop the server
2. Go into the plugin folder (/plugins/BetterTeams/) and rename the folder called teamInfo to teamInfoOld this is so no information is lost if you do the process wrong
3. Rename the file teams.yml to teamsOld.yml this is once again to ensure no data is lost
4. Rename the file teamsBACKUP.yml to teams.yml
5. Start up your server on whatever version of betterteams you want

**Closed by booksaw** 2021-07-17 09:13 UTC
Labels: bug
