### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by zumsty** [booksaw/BetterTeams#406] opened 2023-02-13 04:20 UTC
### What is the bug?

when i leave my team it say something went wsay something went wrong while executing thatrong while executing that command. please report it to the server owner

### Expected Behaviour

fix it

### How to Reproduce

1./team leave 
2.then it show something went wsay something went wrong while executing thatrong while executing that command. please report it to the server owner

### Error message

something went wsay something went wrong while executing thatrong while executing that command. please report it to the server owner

### Output of /teama version

idk

**Comment by booksaw** [comment] 2023-02-13 08:43
There will be a bug report in the server console at the same time as the error occurred. please can you send a full copy of that error to this bug report.

**Comment by AjMaacc** [comment] 2023-03-01 02:20
```
[02:18:30 ERROR]: Something went wrong while executing the command, please report this https://github.com/booksaw/BetterTeams/issues/new/choose
[02:18:30 WARN]: java.lang.NullPointerException: Cannot invoke "com.booksaw.betterTeams.TeamPlayer.getPlayer()" because "teamPlayer" is null
[02:18:30 WARN]:        at BetterTeams-4.6.2.jar//com.booksaw.betterTeams.team.MemberListComponent.remove(MemberListComponent.java:60)
[02:18:30 WARN]:        at BetterTeams-4.6.2.jar//com.booksaw.betterTeams.Team.removePlayer(Team.java:658)
[02:18:30 WARN]:        at BetterTeams-4.6.2.jar//com.booksaw.betterTeams.Team.removePlayer(Team.java:644)
[02:18:30 WARN]:        at BetterTeams-4.6.2.jar//com.booksaw.betterTeams.commands.teama.LeaveTeama.onCommand(LeaveTeama.java:28)
[02:18:30 WARN]:        at BetterTeams-4.6.2.jar//com.booksaw.betterTeams.commands.ParentCommand.onCommand(ParentCommand.java:135)
[02:18:30 WARN]:        at BetterTeams-4.6.2.jar//com.booksaw.betterTeams.BooksawCommand.runExecution(BooksawCommand.java:72)
[02:18:30 WARN]:        at BetterTeams-4.6.2.jar//com.booksaw.betterTeams.BooksawCommand.lambda$execute$0(BooksawCommand.java:59)
[02:18:30 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run()
[02:18:30 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftAsyncTask.run()
[02:18:30 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run()
[02:18:30 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[02:18:30 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[02:18:30 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by TH3N3WN00B** [comment] 2023-03-10 01:30
I'm getting a similar error but when I try to kick a player off a team

`09.03 22:27:02 [Server] INFO _Samux issued server command: /team kick ExelGM
09.03 22:27:02 [Server] ERROR Something went wrong while executing the command, please report this https://github.com/booksaw/BetterTeams/issues/new/choose
09.03 22:27:02 [Server] WARN java.lang.NullPointerException
09.03 22:27:02 [Server] WARN at java.base/java.util.Objects.requireNonNull(Objects.java:208)
09.03 22:27:02 [Server] WARN at BetterTeams-4.6.2.jar//com.booksaw.betterTeams.commands.team.KickCommand.onCommand(KickCommand.java:43)
09.03 22:27:02 [Server] WARN at BetterTeams-4.6.2.jar//com.booksaw.betterTeams.commands.presets.TeamSubCommand.onCommand(TeamSubCommand.java:39)
09.03 22:27:02 [Server] WARN at BetterTeams-4.6.2.jar//com.booksaw.betterTeams.commands.ParentCommand.onCommand(ParentCommand.java:135)
09.03 22:27:02 [Server] WARN at BetterTeams-4.6.2.jar//com.booksaw.betterTeams.BooksawCommand.runExecution(BooksawCommand.java:72)
09.03 22:27:02 [Server] WARN at BetterTeams-4.6.2.jar//com.booksaw.betterTeams.BooksawCommand.lambda$execute$0(BooksawCommand.java:59)
09.03 22:27:02 [Server] WARN at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
09.03 22:27:02 [Server] WARN at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
09.03 22:27:02 [Server] WARN at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
09.03 22:27:02 [Server] WARN at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
09.03 22:27:02 [Server] WARN at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
09.03 22:27:02 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:833)`

**Comment by booksaw** [comment] 2023-03-14 16:58
@AjMaacc @TH3N3WN00B 
Please could you provide the version of the plugin you are using. 
If you have not already, update to the latest version and in `config.yml` set `rebuildLookups` to true and restart your server.
If the issue is still persisting after that occurs please let me know.

**Comment by TH3N3WN00B** [comment] 2023-03-14 18:04
> @AjMaacc @TH3N3WN00B Please could you provide the version of the plugin you are using. If you have not already, update to the latest version and in `config.yml` set `rebuildLookups` to true and restart your server. If the issue is still persisting after that occurs please let me know.

hello, im using this version:

![image](https://user-images.githubusercontent.com/10799738/225097258-cc349ca5-838b-4cfc-8869-4035210a3a6e.png)

**Comment by booksaw** [comment] 2023-03-14 18:54
@TH3N3WN00B thanks for the quick response, have you tried setting `rebuildLookups` to true in `config.yml` then restarting your server?

**Comment by TH3N3WN00B** [comment] 2023-03-21 02:20
> 

Seems like it was fixed, thanks for the help! sorry for the delay btw

**Comment by booksaw** [comment] 2023-03-21 09:42
This bug has been fixed and the patch will be included in the next update. Thank you for reporting.

**Closed by booksaw** 2023-03-21 09:42 UTC
Labels: bug, question
