### ISSUE TITLE
[FEATURE] Ally chat has plugin prefix

### ISSUE THREAD

**Issue by srnyx** [booksaw/BetterTeams#268] opened 2021-11-13 04:42 UTC
![image](https://user-images.githubusercontent.com/25808801/141605904-61753007-2876-40db-8d38-6e971b6727ac.png)

```yml
allychat:
  syntax: '&8[&6&lALLY&8] &e%s&a%s &7» &r%s'
```

**Comment by Aadi-mone** [comment] 2021-11-13 06:07
that's not a bug, you have added a prefix in the messages config.
that will be there as normal change it if you don't want it there in the config.

**Comment by srnyx** [comment] 2021-11-13 14:30
> that's not a bug, you have added a prefix in the messages config. that will be there as normal change it if you don't want it there in the config.

So it's supposed to be shown with ally chat's syntax but not team chat's syntax????

**Comment by Aadi-mone** [comment] 2021-11-13 14:46
that's the way how booksaw coded it, and I tested both team chat and ally chat and works fine for me.
as you can see booksaw removed the bug label and added the enchantment label, he might want to add this in the feature update or something, this is not a bug btw.

~ Greetings
Adarsh A

**Comment by srnyx** [comment] 2021-11-13 14:56
> I tested both team chat and ally chat and works fine for me

![image](https://user-images.githubusercontent.com/25808801/141648385-298a0fda-16a1-437d-965e-4773a4ab6e87.png)
![image](https://user-images.githubusercontent.com/25808801/141648389-163606e9-c85b-497d-a950-f67288f8f3f6.png)

**Comment by Aadi-mone** [comment] 2021-11-13 16:20
🤦‍♂️
```yml

language: en
storageType: YAML
prefix: false
prefixFormat: '&7[&6Teams&7] '

```

**Comment by srnyx** [comment] 2021-11-13 16:27
> 🤦‍♂️
> 
> ```yaml
> language: en
> storageType: YAML
> prefix: false
> prefixFormat: '&7[&6Teams&7] '
> ```

I don't want to remove the plugin's prefix. I just want team chat and ally chat to be consistent (either don't have the plugin's prefix or do, but I prefer they don't).

**Comment by Aadi-mone** [comment] 2021-11-14 06:18
That's currently not possible.
If you want that to work code it yourself and make a pull request as u did.

~ Greetings
Adarsh A

**Comment by srnyx** [comment] 2021-11-14 15:20
> That's currently not possible

That's why I'm suggesting it 🤦‍♂️

**Comment by Aadi-mone** [comment] 2021-11-15 08:36
🤦‍♂️
![44444444](https://user-images.githubusercontent.com/87631878/141748823-1d296a3b-4d9d-45a9-b5a6-6d27c33ca746.PNG)



![4455444](https://user-images.githubusercontent.com/87631878/141748830-409b10ba-a169-48da-aed1-c748519762b5.PNG)

**Comment by booksaw** [comment] 2021-12-22 19:28
This feature has been implemented and will be included in the next update. Thank you for the suggestion.

**Closed by booksaw** 2021-12-22 19:28 UTC
Labels: enhancement
