### ISSUE TITLE
[FEATURE] Score increase methods

### ISSUE THREAD

**Issue by Broken-Java** [booksaw/BetterTeams#356] opened 2022-06-26 23:52 UTC
### What is the feature request for?

More ways to increase score. For example, killing an X amount of X mobs = X score / Crafting X amount of X items = X score / or even an economy based feature, buying X amount of score for X amount of in-game currency.

**Comment by booksaw** [comment] 2024-02-24 14:09
Duplicate of #422

**Closed by booksaw** 2024-02-24 14:09 UTC
Labels: enhancement (medium)
