### ISSUE TITLE
[BUG] Latency with SQL Placeholders 

### ISSUE THREAD

**Issue by Skytoone** [booksaw/BetterTeams#533] opened 2024-01-02 17:53 UTC
### What is the bug?

When I switch BetterTeams to SQL, the placeholderAPI have latency. For example, in my tab I have the top 10 teams, and when we connect to the server the tab plugin takes 10-15 seconds to display.
The same goes for DeluxeMenus, which lets you choose your teams, and there's also 10-15 seconds of latency.

### Expected Behaviour

Less latency 

### How to Reproduce

When I switch the plugin to SQL, I get the error in the logs when restarting the server.

### Error message

[18:42:12 INFO]: [BetterTeams] Disabling BetterTeams v4.8.3
[18:42:14 WARN]: java.sql.SQLException: No operations allowed after statement closed.
[18:42:14 WARN]: at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
[18:42:14 WARN]: at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
[18:42:14 WARN]: at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
[18:42:14 WARN]: at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
[18:42:14 WARN]: at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
[18:42:14 WARN]: at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:82)
[18:42:14 WARN]: at com.mysql.cj.jdbc.StatementImpl.resetCancelledState(StatementImpl.java:776)
[18:42:14 WARN]: at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:935)
[18:42:14 WARN]: at BetterTeams.jar//com.booksaw.betterTeams.team.storage.team.SQLTeamStorage.getWarps(SQLTeamStorage.java:191)
[18:42:14 WARN]: at BetterTeams.jar//com.booksaw.betterTeams.team.WarpListComponent.load(WarpListComponent.java:13)
[18:42:14 WARN]: at BetterTeams.jar//com.booksaw.betterTeams.Team.<init>(Team.java:346)
[18:42:14 WARN]: at BetterTeams.jar//com.booksaw.betterTeams.team.TeamManager.getTeam(TeamManager.java:73)
[18:42:14 WARN]: at BetterTeams.jar//com.booksaw.betterTeams.team.TeamManager.getTeamByName(TeamManager.java:144)
[18:42:14 WARN]: at BetterTeams.jar//com.booksaw.betterTeams.team.TeamManager.getTeam(TeamManager.java:87)
[18:42:14 WARN]: at BetterTeams.jar//com.booksaw.betterTeams.Team.getTeam(Team.java:87)
[18:42:14 WARN]: at BetterTeams.jar//com.booksaw.betterTeams.integrations.placeholder.TeamPlaceholders.processRankedTeamDataPlaceholder(TeamPlaceholders.java:136)
[18:42:14 WARN]: at BetterTeams.jar//com.booksaw.betterTeams.integrations.placeholder.TeamPlaceholders.onPlaceholderRequest(TeamPlaceholders.java:90)
[18:42:14 WARN]: at PlaceholderAPI-2.11.5.jar//me.clip.placeholderapi.PlaceholderHook.onRequest(PlaceholderHook.java:32)
[18:42:14 WARN]: at PlaceholderAPI-2.11.5.jar//me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119)
[18:42:14 WARN]: at PlaceholderAPI-2.11.5.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71)
[18:42:14 WARN]: at PlaceholderAPI-2.11.5.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:99)
[18:42:14 WARN]: at TAB v4.1.2.jar//me.neznamy.tab.platforms.bukkit.platform.BukkitPlatform.lambda$registerUnknownPlaceholder$7(BukkitPlatform.java:190)
[18:42:14 WARN]: at TAB v4.1.2.jar//me.neznamy.tab.shared.placeholders.PlayerPlaceholderImpl.request(PlayerPlaceholderImpl.java:146)
[18:42:14 WARN]: at TAB v4.1.2.jar//me.neznamy.tab.shared.placeholders.PlayerPlaceholderImpl.update(PlayerPlaceholderImpl.java:52)
[18:42:14 WARN]: at TAB v4.1.2.jar//me.neznamy.tab.shared.features.PlaceholderManagerImpl.updatePlayerPlaceholder(PlaceholderManagerImpl.java:120)
[18:42:14 WARN]: at TAB v4.1.2.jar//me.neznamy.tab.shared.features.PlaceholderManagerImpl.refresh(PlaceholderManagerImpl.java:67)
[18:42:14 WARN]: at TAB v4.1.2.jar//me.neznamy.tab.shared.cpu.CpuManager.lambda$enable$1(CpuManager.java:77)
[18:42:14 WARN]: at TAB v4.1.2.jar//me.neznamy.tab.shared.cpu.CpuManager.run(CpuManager.java:173)
[18:42:14 WARN]: at TAB v4.1.2.jar//me.neznamy.tab.shared.cpu.CpuManager.lambda$enable$2(CpuManager.java:75)
[18:42:14 WARN]: at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[18:42:14 WARN]: at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[18:42:14 WARN]: at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[18:42:14 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[18:42:14 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[18:42:14 WARN]: at java.base/java.lang.Thread.run(Thread.java:840)
[18:42:14 WARN]: Caused by: com.mysql.cj.exceptions.StatementIsClosedException: No operations allowed after statement closed.
[18:42:14 WARN]: at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[18:42:14 WARN]: at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[18:42:14 WARN]: at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[18:42:14 WARN]: at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[18:42:14 WARN]: at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[18:42:14 WARN]: at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
[18:42:14 WARN]: at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:85)
[18:42:14 WARN]: at com.mysql.cj.jdbc.StatementImpl.checkClosed(StatementImpl.java:336)
[18:42:14 WARN]: at com.mysql.cj.jdbc.StatementImpl.resetCancelledState(StatementImpl.java:773)
[18:42:14 WARN]: ... 28 more

### Output of /teama version

![image_2024-01-02_184827040](https://github.com/booksaw/BetterTeams/assets/68307537/c2913654-d180-4f84-a556-0e4183ebf9d2)

**Comment by booksaw** [comment] 2024-01-03 17:40
Relates to #482

**Comment by booksaw** [comment] 2024-01-27 13:03
(marking as duplicate to clean up the 'open' ticket list) 
Duplicate of #482

**Closed by booksaw** 2024-01-27 13:03 UTC
Labels: bug
