### ISSUE TITLE
[BUG] /team balance

### ISSUE THREAD

**Issue by tnht** [booksaw/BetterTeams#37] opened 2021-01-18 19:38 UTC
After deposit money >999 we cant see first char.
So, you can deposit $1200 and we see only 200.

[https://ibb.co/Njn84KG](https://ibb.co/Njn84KG)

**Comment by booksaw** [comment] 2021-01-18 20:06
![image](https://user-images.githubusercontent.com/13976636/104957644-710ce800-59c6-11eb-8a91-3f44f9b2883c.png)
I have just tried to reproduce, and I have not had the same problem you seem to be encountering (ignore the strange currency symbol, that is another thing) 

For me to fix it, I need more details, screenshots explaining in detail what is happening, and a way to repeatedly reproduce the bug without these things I am just shooting in the dark at what the problem may be. 
At a guess, another plugin is interfering, so I would suggest assessing each of your plugins to see if they could be doing that.

**Comment by tnht** [comment] 2021-01-18 20:16
I have only essentialsx, essentialsxchat, vault and skript without any scripts.
Hmm....

I make reset of plugin and the same thing.
Run server > /team deposit 1000 > /team bal and this error.

**Comment by booksaw** [comment] 2021-01-18 20:33
Could you screenshot the problem please. Ive run that exact command and I am not having the same problem.
If you run that command then restart the server. Could you check in teams.yml what the team balance is stored to be?

**Comment by tnht** [comment] 2021-01-18 20:36
In teams.yml is correct value.

**Comment by tnht** [comment] 2021-01-18 20:39
I'm using papermc

**Comment by booksaw** [comment] 2021-01-18 20:46
Paper will not have an effect, anything which works on spigot will work on paper. 
Could you screenshot the problem please, commands, messages, teams.yml etc. (third time of me asking) <- do not ignore this as I will no longer reply if this does not happen

As I have said, I cannot reproduce this error following the steps you have provided. I have also seen no evidence of this bug, so currently there is no way of me fixing it, as I don't really know what I am fixing.

**Comment by tnht** [comment] 2021-01-18 20:53
https://imgur.com/a/RitHc4q

**Comment by booksaw** [comment] 2021-01-18 21:02
Thank you. 
Is the currency symbol just strange for betterteams, or is it like that if you do /bal?

I have one idea of what could be causing that and I will check if that is causing the problem.

**Comment by tnht** [comment] 2021-01-18 21:04
in /money i have $ but in /team bal i have polish zloty (zł)

**Comment by booksaw** [comment] 2021-01-18 21:15
Sorry, im not making myself clear, strange symbol was not very descriptive. 
![image](https://user-images.githubusercontent.com/13976636/104963359-3f9a1980-59d2-11eb-9447-1d6fe6eb6345.png)
Is this symbol intended?

**Comment by tnht** [comment] 2021-01-18 21:17
Yes.

**Comment by tnht** [comment] 2021-01-19 07:32
It's any ideas? :D Why i have polish zloty? it's GEO Location?

**Comment by booksaw** [comment] 2021-01-19 11:12
> It's any ideas? Why i have polish zloty? it's GEO Location?
sorry, I dont understand what this means. 
I have a few. When I have time ill see if they are valid

**Comment by booksaw** [comment] 2021-01-20 18:05
This issue has fixed and will be included in the next update. 

On another note, I notice that you have a translated version of messages.yml, if you are interested in that version of messages.yml being publically available could you join my discord server here: https://discord.gg/JF9DNs3 and check the #anouncements channel. 
I am interested in this as I am aware of many servers that have all had to manually translate their messages.yml file, and if community translations are already available, it will make their life easier.

**Closed by booksaw** 2021-01-20 18:05 UTC
Labels: bug, question
