### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by plumbbow75** [booksaw/BetterTeams#556] opened 2024-02-26 14:13 UTC
### What is the feature request for?

can u guys add the option that we can mix colors so when i make a team i want to be able to give the name multiple colors

### Feature requests are not going to be implemented by booksaw, instead you will have to find another developer to make a pull request to implement the feature.

- [X] I understand

**Comment by booksaw** [comment] 2024-02-26 20:00
Duplicate of #385

**Closed by booksaw** 2024-02-26 20:00 UTC
Labels: enhancement (uncategorised)
