### ISSUE TITLE
 server lag

### ISSUE THREAD

**Issue by STEVE1010101** [booksaw/BetterTeams#163] opened 2021-06-17 06:00 UTC
My server have 50~100 players online same time
and this plugins let server lag
here is reason
also i think can add disable score
so it stop player death event
![image](https://user-images.githubusercontent.com/70594985/122339996-50948a00-cf74-11eb-9e83-8b7a8fc48ed7.png)

**Comment by booksaw** [comment] 2021-06-17 09:20
If all goes to plan #135 will help improve this problem as most of the lag will be identifying the team that a player is attached to (this is inefficient at the moment) 
If you are in the discord could you please pm me your teams.yml file so I can do further testing based on the number of teams your server has to ensure the problem is resolved? You could also do it here but it would be pubically accessible, if you pm it on discord I will not share it with other people.

**Comment by booksaw** [comment] 2021-06-25 16:40
This bug has been fixed and the patch will be included in the next update. Thank you for reporting.

**Closed by booksaw** 2021-06-25 16:40 UTC
Labels: bug
