### ISSUE TITLE
[BUG] Placeholder Thread Creation

### ISSUE THREAD

**Issue by R00tB33rMan** [booksaw/BetterTeams#576] opened 2024-04-02 15:55 UTC
### What is the bug?

Plugins such as FancyHolograms permit unlimited thread creation. Although FancyHolograms should monitor/limit this, BetterTeams should, too, because BetterTeams appears to create threads infinitely.

The author of FancyHolograms claims it's not something he can necessarily resolve, so I instead come to you to resolve this issue.

### Expected Behaviour

Thread limit is capped or managed more efficiently.

### How to Reproduce

1. Install FancyHolograms + BetterTeams
2. Create a leaderboard with FancyHolograms containing the BetterTeams placeholder(s)
3. Have a lot of users within that area and watch as the server massively depreciated in stability

### Error message

None

### Output of /teama version

Storage Method: com.booksaw.betterTeams.team.storage.storageManager.SeparatedYamlStorageManager
Minecraft Version: git-UniverseSpigot-"7b6182b" (MC: 1.20.4)
Language Selected: messages
Online mode: false (Is online mode; running behind proxy)
Player count: 143
Current plugin version: 4.9.0

### Additional Information

spark report: https://spark.lucko.me/8QYQl7BzJm

**Comment by booksaw** [comment] 2024-04-20 14:13
Duplicate of #482

**Closed by booksaw** 2024-04-20 14:13 UTC
Labels: bug
