### ISSUE TITLE
[BUG] User client disconnect / crash 1.20.6

### ISSUE THREAD

**Issue by Sonnelus** [booksaw/BetterTeams#621] opened 2024-07-03 15:49 UTC
### What is the bug?

PaperSpigot 1.20.6
BetterTeams 4.9.4

Users are disconeccted. Log from Minecraft game output:

![obraz](https://github.com/booksaw/BetterTeams/assets/166514702/e818b825-a754-477e-bf13-10b3d7768b12)

### Expected Behaviour

Not to disconnect users

### How to Reproduce

Install Better Teams 4.9.4 on PaperSpigot 1.20.6 and wait...

### Error message

Failed to handle packet net.minecraft.class_5900@49de5649
java.lang.IllegalStateException: Player is either on another team or not on any team. Cannot remove from team 'gigasztos'.
	at net.minecraft.class_269.method_1157(class_269.java:308)
	at net.minecraft.class_634.method_11099(class_634.java:2044)
	at net.minecraft.class_5900.method_34173(class_5900.java:132)
	at net.minecraft.class_5900.method_11054(class_5900.java:18)
	at net.minecraft.class_2600.method_11072(class_2600.java:25)
	at net.minecraft.class_1255.method_18859(class_1255.java:162)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:136)
	at net.minecraft.class_1255.method_5383(class_1255.java:121)
	at net.minecraft.class_310.method_1523(class_310.java:1275)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

### Output of /teama version

BetterTeams 4.9.4. I had to uninstall plugin to give players on my server some comfort, so I dont have a teama version output

### Additional Information

Crashing since 1.20.6

**Comment by booksaw** [comment] 2024-07-30 20:53
Duplicate of #618

**Closed by booksaw** 2024-07-30 20:53 UTC
Labels: bug
