### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by kennethako** [booksaw/BetterTeams#207] opened 2021-07-27 07:10 UTC
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Run command...
2. /team echest

**Expected behaviour**
While running the command /team echest, you can place an items and after you've placed it if you rejoin and get the item and rejoin again, the item you placed will be still there.

**Screenshots**
Dmed the video of demonstration
**Details**
Please provide the following details about your server set-up:
- Spigot version (found by running /version):
- BetterTeams version (found by running /version BetterTeams): 

**Additional context**

**Comment by booksaw** [comment] 2021-07-27 10:06
I have tried to replicate this about 40 times, including making a macro to disconnect from the server as fast as possible, I am assuming I have unintentionally fixed the bug while working on the update.
Let me know if this issue persists after you update to the version which will release later today

Also have you checked the resulting items are not ghost items.

**Comment by kennethako** [comment] 2021-07-27 10:07
Did you do it on a server, perhaps an aternos one?

**Comment by booksaw** [comment] 2021-07-27 10:10
ill get a friend to test on my server. see if its a ping thing

**Comment by kennethako** [comment] 2021-07-27 10:11
Cool, thanks!

**Comment by booksaw** [comment] 2021-07-27 10:21
Alright, my friend cant reproduce it either, im going to release the update in like 10 mins, let me know if after updating the bug still persists and ill investigate it further

**Comment by kedavlar** [comment] 2021-07-27 10:26
same bug found today

**Comment by kennethako** [comment] 2021-07-27 10:29
Awesome, thanks!

**Comment by booksaw** [comment] 2021-07-27 15:19
This bug has been fixed and the patch will be included in the next update. Thank you for reporting.

**Closed by booksaw** 2021-07-27 15:19 UTC
Labels: bug
