### ISSUE TITLE
Placeholder [BUG]

### ISSUE THREAD

**Issue by GoT-HiM** [booksaw/BetterTeams#224] opened 2021-09-01 23:47 UTC
When I enter the% betterTeam_name% team placeholder and I don't have a team, it doesn't send anything. It would be nice if he sent a customizable message like "No Team"

**Comment by booksaw** [comment] 2021-09-02 07:05
For starters the placeholder is `%betterTeams_name%` (note the s at the end of team.

Secondally there is already a way of changing what it says when you do not have a team. Check messages.yml for the message `placeholder.noTeam` and change that to whatever you want.

I am closing this issue as it is not a bug, feel free to make a new one if you have any other difficulties.

**Closed by booksaw** 2021-09-02 07:05 UTC
Labels: bug
