### ISSUE TITLE
[FEATURE] RGB COLORS

### ISSUE THREAD

**Issue by HonzasikCZ** [booksaw/BetterTeams#583] opened 2024-04-12 20:51 UTC
### What is the feature request for?

Add RGB colors support

### Additional Information

like #C00000

### Feature requests are not going to be implemented by booksaw, instead you will have to find another developer to make a pull request to implement the feature.

- [X] I understand

**Comment by booksaw** [comment] 2024-04-15 16:39
Duplicate of https://github.com/booksaw/BetterTeams/issues/353

**Closed by booksaw** 2024-04-15 16:39 UTC
Labels: enhancement (uncategorised)
