### ISSUE TITLE
[BUG] SQL issue

### ISSUE THREAD

**Issue by jurohn** [booksaw/BetterTeams#386] opened 2022-11-19 11:01 UTC
### What is the bug?

When using SQL storage, my server crashed when any player got hit by another player.

See the log for all errors.

When usin YAML there is no problem.

### Expected Behaviour

Probably a sql issue that can be fixed.

### How to Reproduce

Hitting a player i guess when using SQL storage.

INFO Plugins (49): AutoCommands, BetterRTP, BetterTeams, BuycraftX, Chunky, Citizens, CMILib, CoreProtect, DecentHolograms, DeluxeMenus, Denizen, Essentials, EssentialsChat, EssentialsSpawn, ExcellentCrates, GSit, HomeGUI, ImageOnMap, InventoryRollbackPlus, InvSeePlusPlus, InvSeePlusPlus_Clear, InvSeePlusPlus_Give, LiteBans, LuckPerms, LWC, LWCTrust, NBTAPI, NexEngine, NoChatReports, Pl-Hide-Pro, PlaceholderAPI, Plan, PlugManX (PlugMan), ProtocolLib, PvPManager, Sentinel, ShopGUIPlus, ShopGUIPlus-SellGUI, SimpleScore, spark, SuperVanish, TAB, VariableEnderChests, Vault, Vulcan, WorldEdit, WorldGuard, WorldGuardExtraFlags, zAuctionHouseV3

Note: tested it without PvPManager. No changes.

### Error message

[mysql.txt](https://github.com/booksaw/BetterTeams/files/10046786/mysql.txt)

### Output of /teama version

19.11 11:01:22 [Server] INFO [BetterTeams] Storage Method: com.booksaw.betterTeams.team.storage.storageManager.SeparatedYamlStorageManager
19.11 11:01:22 [Server] INFO [BetterTeams] Minecraft Version: git-Paper-265 (MC: 1.19.2)
19.11 11:01:22 [Server] INFO [BetterTeams] Current plugin version: 4.5.0

**Comment by booksaw** [comment] 2022-12-16 17:33
I think this is caused by betterteams not running data processing on an individual thread.
If I find time, I intend to make betterteams function asynchronously, but with my current amount of free time this will not be soon. It may be worth moving to YAML storage instead of SQL, as if the database connection times-out, it will not cause problems.

**Comment by booksaw** [comment] 2022-12-16 17:39
Relocating all discussion to #317 as it would appear the bug is caused by this.

**Closed by booksaw** 2022-12-16 17:39 UTC
Labels: bug
